lib/screen/admin_dashboard.dart, pubspec.lock, pubspec.yaml
##🎯Purpose
Implements the "No Complaints Found" message for the Admin Dashboard as requested in issue #11.
- Added conditional rendering in the complaints ListView  
- Display centered message with inbox icon when no complaints exist
- Show contextual messages for "no data" vs "empty search results"
- Maintained all existing functionality for complaint management
- ✅ Code review completed - logic is sound
- ❌ Unable to test locally due to Firebase configuration requirements
- 🔍 **Request functional testing during review process**
Could maintainers please:
- Test functionality with live Firebase data
- Verify UI displays correctly across different devices
- Check for any needed styling adjustments
Closes #11
Ready for review! 🚀
=> Add 'No Complaints Found' message for Admin Dashboard

README.md
#4 
- Added a structured Table of Contents to improve navigation and readability of the README file.
- @Prateek9876 
-
=> Docx : Added table of contents to README

lib/screen/admin_dashboard.dart
Fixes [Issue #20](https://github.com/Prateek9876/NagarVikas/issues/20)
Implemented the Dismissible widget to allow admins to manage complaints with swipe gestures. Swiping left marks a complaint as resolved, while swiping right prompts confirmation to delete the complaint.
=> fixed admin dashboard

lib/components/shared_issue_form.dart, pubspec.lock
---
This PR updates the location autofill logic in the shared issue form using the geolocator package. It replaces deprecated desiredAccuracy usage and improves the autofill format to display more accurate address data (sub-locality, street, city, state, country, ISO code).
- Fixes #75 
- Closes #75 
- Relates to #75 
---
---
1. Enhanced location string to show full formatted result instead of just city and state
2. Added fallback handling for permission issues and guided user to settings if required
- `lib/components/shared_issue_form.dart` - Improved …
=> Fixed Geo Locality issue by adding subLocality and other parameters

.gitignore, lib/screen/ComplaintDetailPage.dart, lib/screen/admin_dashboard.dart
---
1. Enhances the admin experience with improved dashboard UI.
2. Adds a new ComplaintDetailPage for viewing full complaint details.
3. Includes image and video preview functionality with play/pause and mute/unmute controls.
4. UI refinements across both the dashboard and complaint details.
- Closes #74 
---
---
1. **Admin Dashboard UI**: Redesigned layout for complaints list with search bar and better styling.
2. New **ComplaintDetailPage.dart**: Shows all data related to a complaint, including user info.
3. **Media Preview**: Integrated image preview and video preview with playback and audio controls.
4. **Gitignore**: Added …
=> Admin video preview

lib/components/shared_issue_form.dart
---
Implements a character counter for the complaint description field with a visual red color warning when the user exceeds or hits the 250-character limit. Also updated the background color to pure white for consistency.
- Fixes #38 
---
---
1. Added character counter for complaint description field to give live feedback on how many characters are remaining.
2. Counter turns red and bold when the limit of 250 characters is reached or exceeded.
3. Enforced max character limit in the TextField using maxLength: 250 and buildCounter: null for cleaner UI.
4. Updated background color to pure white (Colors.white)
- `lib/components/shared_issue_form.dart` - Added …
=> Input limit description 250 char

.vscode/settings.json, android/app/build.gradle, android/app/src/main/kotlin/com/example/MyFirebaseMessagingService.kt, android/gradle/wrapper/gradle-wrapper.properties, lib/main.dart, lib/screen/ComplaintDetailPage.dart, lib/screen/admin_dashboard.dart, lib/screen/analytics_dashboard.dart, lib/screen/discussion.dart, lib/screen/issue_selection.dart, lib/screen/logo.dart, lib/screen/my_complaints.dart, lib/screen/register_screen.dart, lib/service/ConnectivityService.dart, lib/widgets/bar_chart_widget.dart, lib/widgets/bottom_nav_bar.dart, lib/widgets/pie_chart_widget.dart, pubspec.lock, pubspec.yaml
---
This PR implements a fully redesigned and responsive Admin Analytics Dashboard for the NagarVikas app. The dashboard now supports a modern UI with elegant cards, charts, dark mode support, and animations.
- Fixes #37 
- Closes #37 
---
---
1. **Change 1**: Implemented a modern, clean Analytics UI with cards, charts, and themes.
2. **Change 2**: Added manual dark mode toggle with dynamic theming.
3. **Change 3**: Integrated animated Pie Chart and Bar Chart with real-time data from Firebase
- `path/to/file1.tsx` - lib/admin/analytics_dashboard.dart
- `path/to/file2.ts` -lib/widgets/bar_chart_widget.dart
- `path/to/file3.vue` -  lib/widgets/pie_chart_widget.dart
---
---
---
---
fl_chart: ^0.66.0 …
=> Admin analytics dashboard

lib/screen/issue_selection.dart
- Fixed merge conflicts.
- Made sure the 2048 Game shows up in the drawer .
- Made all drawer items look the same.
Fixes #98
=> Fixed drawer alignment

android/gradle.properties, lib/screen/admin_dashboard.dart, lib/screen/issue_selection.dart, lib/widgets/exit_confirmation.dart, pubspec.lock, pubspec.yaml
---
This PR implements a clean and interactive in-app notification system for the admin panel. Now, whenever a new complaint is submitted by a user, the admin is notified in real-time through a red bell badge and a detailed notification dialog.
- Closes #121 
- Relates to #121 
---
---
1. **Change 1**: Implemented a persistent and real-time in-app notification system to alert admin when a new complaint is filed.
- `path/to/file1.tsx` -lib/admin_dashboard.dart – Added notification bell icon, red dot counter, and notification dialog 
---
---
---
---
---
---
This PR does not include push notifications (like FCM) — it only handles local in-app alerts while the …
=> 🔔 Added in-app notification system for new complaints (#121)

lib/components/image_compression_util.dart, lib/components/shared_issue_form.dart, pubspec.yaml
Added image compression on the shared issue form.
This PR addresses [Issue #7](https://github.com/Prateek9876/NagarVikas/issues/7) by adding image compression functionality to improve performance and reduce upload sizes.
Changes include:
Added image_compression_util.dart in lib/components/
Updated pubspec.yaml to include required image compression dependencies
=> Image compression added

android/gradle.properties, lib/components/shared_issue_form.dart, lib/main.dart, lib/screen/ComplaintDetailPage.dart, lib/screen/login_page.dart, lib/service/local_status_storage.dart, pubspec.lock, pubspec.yaml
---
_A clear and concise description of what this pull request accomplishes._
- Fixes #(issue number)
- Closes #(issue number)
- Relates to #(issue number)
---
---
- `path/to/file1.tsx` - Brief description of changes
- `path/to/file2.ts` - Brief description of changes
- `path/to/file3.vue` - Brief description of changes
---
---
---
---
> ⚠️ **Note:** _Do not change or add …
=> Notification Changes

lib/screen/login_page.dart
---
Changed the email verification message shown during login.
"You need to verify your email before logging in. Please check your inbox (and spam folder) for the verification email."
- Fixes #140 
- Closes #140 
---
---
- `login_page.dart`
---
---
---
---
> ⚠️ **Note:** _Do not change or add dependencies unless absolutely necessary. Please justify any dependency changes …
=> notification updated in loginpage

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/general_inquiry.yml
---
Added Issue template
- Fixes #51 
- Closes #51 
- Relates to #51 
---
---
- `path/to/file1.tsx` - Brief description of changes
- `path/to/file2.ts` - Brief description of changes
- `path/to/file3.vue` - Brief description of changes
---
---
---
---
**Dependency change …
=> Added Issue Template

lib/service/local_status_storage.dart, lib/widgets/chatbot_wrapper.dart
---
_A clear and concise description of what this pull request accomplishes._
- Fixes #(issue number)
- Closes #(issue number)
- Relates to #(issue number)
---
---
- `path/to/file1.tsx` - Brief description of changes
- `path/to/file2.ts` - Brief description of changes
- `path/to/file3.vue` - Brief description of changes
---
---
---
---
> ⚠️ **Note:** _Do not change or add …
=> Admin notify #135

CONTRIBUTING.md
This PR adds a complete CONTRIBUTING.md file to help new contributors—especially those participating via GSSoC—understand how to contribute effectively to the NagarVikas project.
✅ Includes:
- Full tech stack overview (Flutter, Firebase, Cloudinary, Geolocator, Notifications)
- Step-by-step setup instructions for development environment
- Folder structure and file role explanation
- Git contribution workflow (forking, branching, commit, PR)
- Best practices and testing recommendations
- Firebase + location permissions info for Android and iOS
This guide improves onboarding for new contributors and enhances project maintainability.
Closes  issue #193
=> 📝 Added full CONTRIBUTING.md with setup guide and contribution workflow

android/gradle.properties, lib/screen/contact.dart, lib/screen/feedback.dart, pubspec.yaml
---
_A clear and concise description of what this pull request accomplishes._
- Fixes #(issue number)
- Closes #(issue number)
- Relates to #(issue number)
---
---
- `path/to/file1.tsx` - Brief description of changes
- `path/to/file2.ts` - Brief description of changes
- `path/to/file3.vue` - Brief description of changes
---
---
---
---
> ⚠️ **Note:** _Do not change or add …
=> Improved ui in Contact us and Feedback Page #181 Level 2

lib/screen/admin_dashboard.dart, lib/screen/favourites.dart, pubspec.yaml
---
---
This PR introduces a **favourite feature** that allows **admins** to mark specific complaints as favourites. Once a complaint is favourited, it is stored and accessible via a **dedicated "Favourites" section** added to the **sliding menu bar** in the admin dashboard. This enhancement improves complaint management by enabling easier access to high-priority or frequently referenced complaints.
* Closes #64
---
---
---
---
---
---
---
---
---
* Can be extended in future for users to favourite their own complaints.
* Consider adding export/share functionality for favourites.
---
@preetidas60 
---
=> Added Star/Favorite to Complaints (Admin) #64 Level 3

README.md
---
Fixes: #199 
This PR adds a "📁 Project Structure" section to the README.md file to help users and contributors better understand the organization of files and directories in the repository.
🔘Provides a clear overview of the repo layout.
🔘Improves onboarding experience for new developers.
🔘Makes it easier to locate files and understand their purpose.
- Fixes  #199
- Closes #199
- Relates to  #199
---
---
1. **Change 1**: Added a tree-style project structure using Markdown code block.
2. **Change 2**: Included brief comments for each folder/file to explain their …
=> update readme file by adding project structure(#199)

lib/screen/admin_dashboard.dart, lib/screen/favourites.dart, pubspec.lock
---
Redesigned the admin dashboard with a modern layout, real-time complaint updates and filtering. Also revamped the Favorites page with dynamic data fetching, modular widgets, and improved styling for better user experience.
- Fixes #137 
---
---
---
---
---
---
---
@Prateek9876
=> Improved UI of Admin Dashboard #137 Level 2

lib/screen/done_screen.dart
---
This PR modifies the **success animation** that appears after successfully submitting a complaint. This enhancement improves **user feedback and experience** by clearly indicating successful completion of the process.
- Closes #6 
---
---
1. Integrated an animation widget in the **done screen**.
2. Displayed the animation once the complaint is successfully submitted.
3. Ensured smooth transition and user feedback.
* `lib/screens/done_screen.dart` – Added success animation logic and widget.
---
---
---
---
---
---
* Smooth animation improves user trust and feedback visibility.
* Can be enhanced in the future with celebratory sound or interaction.
@Prateek9876
=> Added Animation on Complaint Submission Success #6 Level 2

lib/screen/discussion.dart, pubspec.yaml
---
This PR is for improving the Discussion Forum's UI
- Fixes #123 
- Closes #123 
- Relates to #123 
---
---
1. **Size of Text Bubbles**: Font size and size of text bubbles increased for better readability
2. **Added 'Message Icon'**
3. **Elevated the App bar**: for aesthetics
4. **Added background animation** 
- `pubspec.yaml` - changed intl version from 0.19.0 to 0.20.2
- `discussion.dart` - All changes mentioned above
---
---
---
---
---
@Prateek9876
=> Improved UI for the Discussion Forum

android/app/build.gradle, android/build.gradle, android/settings.gradle, pubspec.yaml
---
Fixed the project's Gradle configuration by updating from the deprecated version 8.2.1 to the latest stable version 8.3.0. This update ensures compatibility with modern Android development tools, eliminates deprecation warnings, and provides access to the latest security patches and performance optimizations.
- Fixes #222  
---
---
---
---
---
---
---
@Prateek9876
=> Changed Gradle Version 8.2.1 to 8.3.0 #222 Level 2

lib/screen/issue_selection.dart, lib/screen/modern_app_drawer.dart, lib/widgets/chatbot_wrapper.dart, pubspec.yaml
- [ x] ⭐ Yes, I have starred the repository
---
This PR redesigns the Sidebar/Menu for cleaner navigation.  
The previous sidebar was cluttered, with inconsistent icons, misplaced language switch, and unnecessary social links.  
These changes improve navigation flow, consistency, and usability.  
---
- 🎨 Style/UI improvement  
- ✨ New feature (non-breaking change which adds functionality)  
- ⚡ Performance optimization  
- 🧹 Code refactoring  
---
- Sidebar redesigned for cleaner and modern look  
- Improved navigation structure and icon consistency  
- Optimized for smaller screens with scrollable support  
- Language Switch moved neatly to the top corner for better visibility  
- Consistent icons applied across all menu items  
- Social links …
=> Redesigned Sidebar/Menu for Cleaner Navigation #233 Level 3

lib/screen/about.dart, lib/screen/admin_dashboard.dart, lib/screen/analytics_dashboard.dart, lib/screen/complaint_details_page.dart, lib/screen/favourites.dart, lib/screen/feedback.dart, lib/screen/issue_selection.dart, lib/widgets/chatbot_wrapper.dart, pubspec.yaml
---
_Fixed overflow issues for Small Phones and withOpacity is depreciated so we can use with Alpha instead of it._
- Fixes #232
- Closes #232
- Relates to #232
- Fixes #240 
- Closes #240
- Relates to #240
---
---
1. **Change 1**: Fixed overflow issues for Small Phones.
2. **Change 2**: withOpacity is depreciated so we can use with Alpha instead of it.
---
---
---
---
**Breaking …
=> Fixed overflow issues for Small Phones #232 and withOpacity is depreciated so we can use with Alpha instead of it #240

lib/screen/register_screen.dart
---
---
This PR addresses the **validation errors appearing prematurely** on the Sign Up page before users have entered any input. The issue was causing red error text to display immediately when the page loads, creating a poor user experience. The fix ensures that validation errors only appear after users have interacted with the form fields or attempted to submit the form.
* Closes #227 
---
---
---
---
---
---
---
---
---
* This fix improves user experience by showing validation errors only when appropriate.
* Consider implementing similar validation timing fixes across other forms if needed.
---
@Prateek9876 
---
=> Fixed validation errors showing before input on Sign Up page #227 Level 2

lib/screen/profile_screen.dart
- [ x] ⭐ Yes, I have starred the repository
---
This pull request enhances the user interface of the profile section in the user screen by improving visual design, layout, and user experience. The changes focus on making the profile section more intuitive, visually appealing, and user-friendly.
- Fixes #243
---
---
1. **Profile Layout Enhancement**: Improved the overall layout structure of the profile section for better visual hierarchy
2. **Visual Design Updates**: Enhanced styling, colors, and spacing to create a more modern and polished appearance
3. **User Experience Improvements**: Optimized component arrangement and interaction patterns for better usability
- …
=> Redesigned Profile Page #243 Level 3

lib/screen/feedback.dart
---
This pull request significantly enhances the FeedbackPage UI/UX with modern design principles, smooth animations, and improved user experience. The changes transform a basic feedback form into a polished, professional interface that encourages user engagement.
- Closes #235 
---
---
1. **Modern Card-based Layout**: Replaced basic layout with elegant card-based design using shadows and rounded corners
2. **Smooth Animations**: Added TickerProviderStateMixin with animation controllers for interactive feedback
3. **Responsive Design**: Implemented dynamic sizing based on screen height for better mobile experience
4. **Enhanced Rating System**: Improved star rating with hover effects, animations, and contextual feedback messages …
=> Improved the feedback screen for users #235 Level 3

lib/widgets/bar_chart_widget.dart, lib/widgets/bottom_nav_bar.dart, lib/widgets/chatbot_wrapper.dart
---
_Added dark mode to admin dashboard screen in the app and made it persistent._
- Fixes #246 
- Closes #246
- Relates to #246
---
---
1. **Change 1**: Added dark mode to Admin's Dashboard and made it persistent.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Working Dark Mode option in Admin's Dashboard Screen

lib/widgets/bar_chart_widget.dart, lib/widgets/chatbot_wrapper.dart, lib/widgets/pie_chart_widget.dart
---
_withOpacity is depreciated so we can use withAlpha instead of it._
- Fixes #240 
- Closes #240
- Relates to #240
---
---
1. **Change 1**: withOpacity is depreciated so we can use withAlpha instead of it.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> withOpacity is depreciated so we can use withAlpha instead of it

lib/service/local_status_storage.dart, lib/widgets/bar_chart_widget.dart, lib/widgets/pie_chart_widget.dart
---
_Working Dark mode in Authentication pages like Login/Signup pages and made it persistent._
- Fixes #249 
- Closes #249 
- Relates to #249  
---
---
1. **Change 1**: Added dark mode to Authentication pages and made it persistent.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Working Dark mode in Authentication pages like Login/Signup pages

lib/model/game_model.dart
---
Enhanced the 2048 Game UI to fully integrate with the existing theme system, providing consistent dark/light mode support and removing duplicate theme controls.
- Fixes #319
---
---
1. **Theme Integration**: Connected 2048 game to existing `ThemeProvider` system
2. **UI Consistency**: Matched colors, gradients, and styling with app theme
3. **Removed Duplicate Controls**: Eliminated separate theme toggle in game
- `lib/screens/game_2048.dart` - Enhanced UI with theme integration and removed duplicate theme toggle
---
---
@Prateek9876
=> Improved the UI of Game Model with Current Theme #319 Level 3

android/build.gradle, pubspec.yaml
---
_Fixed warning_
- Fixes #305  
- Closes #305 
- Relates to #305 
---
---
1. **Change 1**: Fixed warning.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Fixed warning

lib/screen/issue_selection.dart
---
- Fixes Terms & Conditions popup UI to align with theme (design, typography, button styling).  
- Related Issue: Fixes #262  
---
---
- Updated popup design for consistency  
- Adjusted typography & button styling  
**Files Modified:**  
- `lib/screen/issue_selection.dart`  
---
---
---
---
---
- Popup now matches app design language.  
---
@Prateek9876
=> Updated Terms & Conditions Acceptance Popup #262 Level 3

lib/screen/about.dart
---
---
This PR completely revamps the About page UI to match the app's current theme system with:
- Modern Material 3 design elements
- Full dark/light theme support
- Smooth animations
- Better information organization
- Improved visual hierarchy
---
---
- Complete redesign of About page UI
- Added theme-aware components
- Implemented smooth animations
- Improved information architecture
1. **New Layout**: Organized content into clear sections (App Info, Features, Team, Contact)
2. **Theme Support**: All components now properly adapt to dark/light theme
3. **Animations**: Added subtle entrance animations using animate_do package
4. **Visual Hierarchy**: Improved typography and spacing for better readability
5. …
=> Improved the UI of About NagarVikas Page with Current Theme #316 Level 3

lib/screen/discussion.dart
Enhanced the UI/UX of the discussion forum to improve user experience and visual appeal.
- Fixes #325
---
---
1. **Discussion Forum UI Redesign**: Updated the discussion screen with improved layout and visual elements
2. **Enhanced User Experience**: Improved navigation and interaction patterns
3. **Visual Polish**: Applied consistent styling and better component organization
- `lib/screen/discussion.dart` - Complete UI overhaul with enhanced components and styling
---
---
---
---
---
This PR focuses specifically on UI improvements for the discussion forum as requested in issue #325. The changes maintain all existing functionality while providing a more polished and user-friendly interface.
@Prateek9876
=> Improved the Discussion Forum UI #325

lib/screen/help_center.dart, lib/screen/profile_screen.dart
---
Implements the Help Center page functionality with navigation support from profile screen.
- Fixes #331
---
---
1. **Help Center Page**: Created new help center page with user support features
2. **Navigation Update**: Added navigation routing from profile screen to help center
3. **Bottom Navigation**: Updated navigation bar to support help center access
- `lib/screen/help_center_page.dart` - New help center page implementation
- `lib/screen/profile_screen.dart` - Added help center navigation
---
https://github.com/user-attachments/assets/58abc719-e8f6-41e2-998e-6a6e7425ae84
---
---
- [ x Mobile responsiveness is preserved
---
This PR addresses issue #331 by implementing the missing Help Center page …
=> Added a Help Center Page #331 Level 3

lib/screen/issue_selection.dart
---
_Fixed discussion forum button issue._
- Fixes #312  
- Closes #312 
- Relates to #312 
---
---
1. **Change 1**: Fixed discussion forum button issue.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Fixed discussion forum button issue

lib/screen/admin_dashboard.dart, lib/screen/analytics_dashboard.dart
---
Fixes the bottom navigation issue where logout functionality incorrectly appears when navigating to the Analytics tab. The issue was caused by mismatched navigation logic that expected 3 bottom nav items but only had 2 defined.
- Fixes #314
---
---
- `lib/screen/admin_dashboard.dart` - Fixed bottom navigation tap handler logic
- `lib/screen/analytics_dashboard.dart` - Updated navigation behavior (if applicable)
---
---
---
**Root Cause:** 
The issue occurred because the `_onItemTapped` method was checking for `index == 2` (logout) but the `_bottomNavItems` array only contained 2 items (indices 0 and 1). Additionally, using `Navigator.pushReplacement` was …
=> Solved Bottom Nav Logout Issue in Admin #314

lib/screen/profile_screen.dart, lib/service/local_status_storage.dart, lib/widgets/bottom_nav_bar.dart
---
_The Bottom Nav shows above the drawer._
- Fixes #320  
- Closes #320 
- Relates to #320 
---
---
1. **Change 1**: The Bottom Nav shows above the drawer.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> The Bottom Nav shows above the drawer.

lib/screen/admin_dashboard.dart
---
Enhanced the logout dialog UI in the admin dashboard with modern styling, improved visual hierarchy, and better user experience.
- Fixes #324
---
---
1. **Modern Dialog Design**: Added rounded corners, gradient backgrounds, and proper shadow effects
2. **Enhanced Visual Elements**: Implemented gradient logout icon with shadow for better visual impact
3. **Improved Button Styling**: Created modern button designs with hover effects and better accessibility
4. **Loading State**: Added loading dialog during logout process for better user feedback
- `lib/screen/admin_dashboard.dart` - Enhanced logout dialog UI with modern styling
---
---
---
This enhancement improves the user experience by providing a more polished and modern …
=> Change the UI of the Pop Up Dialog Boxes #324 Level 3

lib/screen/profile_screen.dart
---
Implements fully functional phone number editing in the profile page with Firebase backend integration and validation.
- Fixes #335
---
---
1. **Fixed Edit Dialog**: Added proper TextEditingController and save functionality
2. **Phone Validation**: Implemented 10-digit phone number validation
3. **Firebase Integration**: Connected edit dialog to _updateUserData() method
4. **UI Improvements**: Added proper form validation and user feedback
- `lib/screen/profile_screene.dart` - Fixed _showEditDialog() method and phone validation
---
---
---
@Prateek9876
=> Added Full Working Edit Phone Number with Backend Integration #335 Level 3

lib/screen/complaint_detail_page.dart
---
This PR adds functionality to fetch and display the phone number of users who submitted complaints in the complaint detail page. This enhancement allows administrators to have direct contact information for follow-up communication regarding complaints.
- Fixes #338
---
---
1. **Phone Number Fetching**: Added phone number retrieval from user data when fetching complaint details
2. **UI Enhancement**: Added a new info section to display the user's phone number in the complaint detail view
3. **Fallback Handling**: Implemented proper fallback display ("Not …
=> Added Phone Number Field in Complaint Page with Backend Integration #338 Level 3

lib/screen/discussion.dart, pubspec.yaml
---
This pull request adds image sharing functionality to the discussion forum, allowing users to upload and share images within their discussion posts and comments.
- Fixes #308
---
---
1. **Image Upload Component**: Added image picker functionality allowing users to select images from gallery or camera
2. **Discussion UI Enhancement**: Integrated image upload button and preview functionality in the discussion interface
3. **Image Display**: Implemented proper image rendering and display within discussion posts
- `lib/screen/discussion.dart` - Added image sharing functionality, UI components for image upload/display
- `pubspec.yaml` - Added necessary dependencies for image handling (image_picker, etc.) …
=> Added Send Image in Discussion Page with Backend Integration #308 Level 3

lib/screen/admin_dashboard.dart
---
_Added working filter in admin's dashboard_
- Fixes #344 
- Closes #344  
- Relates to #344  
---
---
1. **Change 1**: Added working filter in admin's dashboard.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Added working filter in admin's dashboard

lib/screen/discussion.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock
---
_Added emoji section and segregated dates_
- Fixes #387 
- Closes #387  
- Relates to #387  
---
---
1. **Change 1**: Added emoji section and segregated dates
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Added emoji section and segregated dates

lib/screen/modern_app_drawer.dart, lib/screen/profile_screen.dart, lib/widgets/bottom_nav_bar.dart
---
_Fixed the blank screen problem on going back from the profile screen._
- Fixes #375 
- Closes #375  
- Relates to #375 
---
---
1. **Change 1**: Fixed the blank screen problem on going back from the profile screen.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Fixed the blank screen problem on going back from the profile screen

lib/screen/about.dart, lib/screen/admin_dashboard.dart, lib/screen/analytics_dashboard.dart, lib/screen/contact.dart, lib/screen/facing_issues.dart, lib/screen/feedback.dart, lib/screen/fun_game_screen.dart, lib/screen/modern_app_drawer.dart, lib/screen/my_complaints.dart, lib/screen/privacy_policy_page.dart, lib/screen/profile_screen.dart, lib/screen/referearn.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock
---
_Fixed the colors of all the headers in the app for both users and admins_
- Fixes #322 
- Closes #322  
- Relates to #322  
---
---
1. **Change 1**: Fixed the colors of all the headers in the app for both users and admins.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Fixed the colors of all the headers in the app for both users and admins

lib/screen/discussion.dart
---
_Allow editing your own message in Discussion Forum_
- Fixes #349 
- Closes #349  
- Relates to #349 
---
---
1. **Change 1**: Allow editing your own message in Discussion Forum.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Allow editing your own message in Discussion Forum

lib/screen/profile_screen.dart
---
Implements a fully functional Edit Profile Page that allows users to update their personal information, upload profile pictures, and manage their account details.
- Fixes #293
---
---
1. **Edit Profile Screen**: Created complete edit profile functionality with form validation
2. **Image Upload**: Implemented profile picture upload with image picker integration
3. **Form Validation**: Added comprehensive input validation for all profile fields
4. **User Experience**: Added loading states, success/error feedback, and responsive design
- `lib/screen/profile_screen.dart` - Added complete edit profile page implementation
---
---
Lightweight implementation with optimized image …
=> Added the Full Working Profile Page #293 Level 3

lib/screen/discussion/discussion.dart
---
_Added Speech to Text functionlity in Discussion Forum_
- Fixes #364 
- Closes #364  
- Relates to #364 
---
---
1. **Change 1**: Added Speech to Text functionlity in Discussion Forum.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Added Speech to Text functionlity in Discussion Forum

lib/screen/discussion/discussion.dart, lib/screen/discussion/message_widgets.dart
---
_Added delete functionality and reply to own messages functionality_
- Fixes #350 
- Closes #350  
- Relates to #350 
---
---
1. **Change 1**: Added delete functionality and reply to own messages functionality.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Added delete functionality and reply to own messages functionality

lib/screen/discussion/discussion.dart
---
_Added text attachment to image/videos in discussion forum and fixed scroll to bottom even if media is there_
- Fixes #400 
- Closes #400 
- Relates to #400 
---
---
1. **Change 1**: Added text attachment to image/videos in discussion forum and fixed scroll to bottom even if media is there.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Added text attachment to image/videos in discussion forum and fixed scroll to bottom even if media is there.

lib/screen/discussion/discussion.dart
---
_Maximum character limit in message box and scrollable message box so that overflow does not occur. Also fix a reply overlapping issue_
- Fixes #422  
- Closes #422 
- Relates to #422 
---
---
1. **Change 1**: Maximum character limit in message box and scrollable message box so that overflow does not occur. Also fix a reply overlapping issue.
---
---
---
---
**Breaking change …
=> Maximum character limit in message box and scrollable message box so that overflow does not occur. Also fix a reply overlapping issue.

lib/screen/admin_dashboard.dart, lib/screen/admin_drawer.dart
---
Enhanced the admin drawer bar UI to match the overall application theme for better visual consistency.
**Related Issue:** Fixes #285
- Updated admin drawer styling to align with the current theme
- Improved visual consistency across admin interface
- Enhanced user experience for admin users
- `lib/screen/admin_dashboard.dart` - Updated drawer integration
- `lib/screen/admin_drawer.dart` - Enhanced drawer theme styling
This PR focuses specifically on visual theme alignment for the admin drawer component, improving the overall admin interface consistency.
@Prateek9876
=> Improved the Admin Drawer UI #285 Level 3

lib/screen/discussion/discussion.dart, lib/screen/discussion/message_widgets.dart
---
Add upvote and downvote functionality to messages in the discussion forum, allowing users to express approval or disapproval of content.
- Fixes #361
1. **Vote Storage**: Added Firebase vote tracking system with user vote history
2. **Toggle Functionality**: Implemented click-to-vote, click-again-to-remove behavior
3. **Visual Feedback**: Added vote count display and active state indicators
4. **User Permissions**: Integrated with existing ban system to prevent banned users from voting
- `lib/screen/discussion/discussion.dart` - Added voting logic, vote storage, and user interaction handlers
- `lib/screen/discussion/message_widgets.dart` - Added voting UI components with animations and vote count display
The voting system …
=> Added the Feature to Upvote and Downvote in Discussion Forum #361

android/app/src/main/AndroidManifest.xml, lib/screen/register_screen.dart
---
Implements optional OTP verification method for user registration with configurable phone verification that can be easily enabled/disabled based on Firebase billing availability.
- Fixes #436
---
---
1. **Optional Phone OTP Verification**: Added complete phone number OTP verification flow using Firebase Auth
2. **Configurable Feature Flag**: Implemented `ENABLE_PHONE_VERIFICATION` constant to toggle verification on/off
3. **Enhanced UI**: Updated registration form with OTP input fields and verification status indicators
4. **Graceful Fallback**: Registration works with or without phone verification enabled
- `android/app/src/main/AndroidManifest.xml` - Added SMS retrieval permissions for OTP auto-fill
- `lib/screen/register_screen.dart` - Complete phone OTP …
=> Added the OTP Verification Method Via SMS #436 Level 3

lib/screen/profile_screen.dart
Updated phone number edit functionality in the profile page to include OTP verification for enhanced security.
- Fixes #435
---
---
- `lib/screen/profile_screen.dart` - Added OTP verification for phone number editing
---
---
---
This update adds an extra layer of security when users want to change their phone number, ensuring the new number belongs to the user through OTP verification.
@Prateek9876
=> Updated the Phone Number Edit Functionality with OTP Verification #435

lib/screen/profile_screen.dart, lib/screen/report_issue_service.dart
---
_Working Report Issue_
- Fixes #438  
- Closes #438 
- Relates to #438 
---
---
1. **Change 1**: Working Report Issue.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Working Report Issue

functions/index.js, lib/screen/discussion/discussion.dart, lib/screen/discussion/message_reporting_screen.dart
---
_Made report in Discussion Forum from User's POV_
- Fixes #445  
- Closes #445 
- Relates to #445 
---
---
1. **Change 1**: Made report in Discussion Forum from User's POV.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Made report in Discussion Forum from User's POV

functions/index.js, lib/screen/admin_dashboard.dart, lib/screen/admin_drawer.dart, lib/screen/discussion/discussion.dart, lib/screen/discussion/message_reporting_screen.dart, lib/screen/my_complaints.dart, lib/screen/reports_dashboard.dart, pubspec.lock
---
_Message Box no visible bug, Long press overflow issue (for admin) and Shimmers according to dark mode_
- Fixes #452  
- Closes #452 
- Relates to #452 
---
---
1. **Change 1**: Message Box no visible bug, Long press overflow issue (for admin) and Shimmers according to dark mode.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Message Box no visible bug, Long press overflow issue (for admin) and Shimmers according to dark mode

lib/screen/discussion/message_widgets.dart, lib/screen/discussion/poll_creation_widget.dart, lib/screen/discussion/poll_message_widget.dart
---
_The poll can be deleted only by the creator (not even admin)_
- Fixes #464 
- Closes #464 
- Relates to #464 
---
---
1. **Change 1**: The poll can be deleted only by the creator (not even admin).
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> The poll can be deleted only by the creator (not even admin)

lib/screen/discussion/discussion.dart, lib/screen/discussion/message_widgets.dart, lib/screen/discussion/poll_message_widget.dart
---
_The name while seeing votes of the poll in discussion forum is showing of only that person who created it_
- Fixes #463 
- Closes #463 
- Relates to #463 
---
---
1. **Change 1**: The name while seeing votes of the poll in discussion forum is showing of only that person who created it.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> The name while seeing votes of the poll in discussion forum is showing of only that person who created it

lib/screen/admin/admin_dashboard.dart, lib/screen/discussion/poll_message_widget.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock
---
_Fixed loading problem when polls are deleted_
- Fixes #474 
- Closes #474 
- Relates to #474 
---
---
1. **Change 1**: Fixed loading problem when polls are deleted.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Fixed loading problem when polls are deleted

lib/screen/discussion/discussion.dart, lib/screen/discussion/message_widgets.dart
---
This pull request implements message reactions functionality in the discussion forum, allowing users to long-press on messages to react with emojis. This enhancement improves user engagement and creates a more interactive, modern chat/forum experience.
- Fixes #454
---
---
1. **Long-press Gesture Recognition**: Added long-press gesture detection on message widgets to trigger reaction picker
2. **Emoji Reaction Picker**: Implemented a custom emoji picker that appears on long-press with common reaction emojis (👍, ❤️, 😂, 😮, 😢, 😡)
3. **Reaction Display**: Added visual representation of reactions below messages with count indicators
4. **Reaction State …
=> Added the Feature to React on a Message #454 Level 3

android/app/src/main/AndroidManifest.xml, lib/widgets/mention_text_widget.dart
---
Fixed issue where links sent to the discussion forum were displayed as plain text instead of clickable links.
**Fixes:** #466
- Modified `lib/widgets/mention_text_widget.dart` to detect and render URLs as clickable links
- Updated `android/app/src/main/AndroidManifest.xml` for proper link handling permissions
- `lib/widgets/mention_text_widget.dart` - Added URL detection and clickable link rendering
- `android/app/src/main/AndroidManifest.xml` - Updated manifest for link handling
---
@Prateek9876
=> Fixed Clickable Links #466 Level 3

lib/screen/discussion/discussion.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock
---
_Fixed Discussion Forum Formatting_
- Fixes #477 
- Closes #477 
- Relates to #477 
---
---
1. **Change 1**: Fixed Discussion Forum Formatting.
---
---
---
---
---
---
@Prateek9876 
@Shibai419
=> Fixed Discussion Forum Formatting
